-- ─────────────────────────────────────────────────────────────────────────────
-- schema.sql
-- Art & Craft E-commerce — PostgreSQL Schema for AWS RDS
-- Run this on your RDS instance after creation:
--   psql -h YOUR_RDS_HOST -U artcraft_admin -d artcraft -f schema.sql
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ─── Products Table ───────────────────────────────────────────────────────────
-- Mirrors the Supabase 'products' table exactly so your exported data
-- imports without any column renaming.
CREATE TABLE IF NOT EXISTS products (
  id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          TEXT NOT NULL,
  description   TEXT,
  price         NUMERIC(10,2) NOT NULL DEFAULT 0,
  regular_price NUMERIC(10,2),
  offer_price   NUMERIC(10,2),
  category      TEXT,
  stock         INTEGER NOT NULL DEFAULT 0,
  is_published  BOOLEAN NOT NULL DEFAULT FALSE,
  image         TEXT,
  images        JSONB NOT NULL DEFAULT '[]',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every UPDATE
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_products_is_published ON products (is_published);
CREATE INDEX IF NOT EXISTS idx_products_category     ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_created_at   ON products (created_at DESC);

-- ─── Users Table ─────────────────────────────────────────────────────────────
-- Maps Cognito user sub (UUID) to additional profile data.
-- Cognito handles passwords + sessions — this stores extra metadata.
CREATE TABLE IF NOT EXISTS users (
  id         UUID PRIMARY KEY,  -- Cognito user sub
  email      TEXT UNIQUE NOT NULL,
  name       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Sample data (optional — remove before prod) ─────────────────────────────
-- INSERT INTO products (name, description, price, regular_price, category, stock, is_published, images)
-- VALUES (
--   'Handmade Ceramic Bowl',
--   'Beautifully wheel-thrown ceramic bowl, food-safe glaze.',
--   999.00, 1299.00, 'Ceramics', 10, true,
--   '["https://example.cloudfront.net/products/sample.jpg"]'
-- );
